import {planet,initialState,tickCompanion,interactCompanion,boss,daySeed,validateBoss,survivalHeuristic,rng} from './engine.mjs';
import {locations,events} from './data.mjs';
import {load,save,KEY} from './storage.mjs';
import {createCombat} from './combat.mjs';
const $=id=>document.getElementById(id);let storage;try{storage=window.localStorage;}catch{}const loaded=load(storage);let state=loaded.state,blocked=!!loaded.warning,currentBoss,view='explore',audio=null,sound=false;
function notify(message){$('notice').textContent=message;}
function persist(){if(blocked)return;const bounded={...state,world:Object.fromEntries(Object.entries(state.world).slice(-500)),reviews:Object.fromEntries(Object.entries(state.reviews).slice(-100))};if(!save(storage,bounded)){blocked=true;notify('浏览器无法保存进度，当前会话仍可继续。');}}
function beep(){if(!sound||!audio)return;try{const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=540;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.1);}catch{}}
function addLog(message){state.log.unshift(message);state.log=state.log.slice(0,30);}
function collect(item){state.inventory[item]=Math.min(9999,(state.inventory[item]||0)+1);}
function button(text,fn){const el=document.createElement('button');el.textContent=text;el.addEventListener('click',fn);return el;}
function p(text,className=''){const el=document.createElement('p');el.textContent=text;el.className=className;return el;}
function eventMaybe(){if(Date.now()-state.lastEvent<20000)return;const r=rng(`${state.seed}:${state.selected}:${state.visited.length}:${state.log.length}`);if(r()>.6)return;const event=events[Math.floor(r()*events.length)];state.lastEvent=Date.now();collect(event.item);addLog(`${event.name}：${event.text}`);notify(event.text);}
function renderExplore(){ $('seed').value=state.seed;$('sector-label').textContent=`星域 ${state.sector+1} / 六个可抵达坐标`;$('previous').disabled=state.sector===0;$('next').disabled=state.sector>=166665;const map=$('map');map.replaceChildren();for(let i=state.sector*6;i<state.sector*6+6;i++){const world=planet(state.seed,i),b=button('',()=>{state.selected=i;if(!state.visited.includes(i)){state.visited.push(i);state.visited=state.visited.slice(-500);addLog(`抵达 ${world.name} / ${world.civilization}`);eventMaybe();}persist();beep();renderExplore();});b.className='planet-button';b.setAttribute('aria-pressed',String(i===state.selected));const orb=document.createElement('span');orb.className='planet-orb';orb.style.setProperty('--hue',world.hue);orb.setAttribute('aria-hidden','true');const name=document.createElement('span');name.textContent=world.name;const desc=document.createElement('small');desc.textContent=`${world.biome}${state.visited.includes(i)?' · 已抵达':''}`;b.append(orb,name,desc);map.append(b);}
 const world=planet(state.seed,state.selected),record=state.world[world.id]||{locations:[]},article=$('planet');article.replaceChildren();const heading=document.createElement('h2');heading.textContent=world.name;article.append(heading,p(`${world.biome} / ${world.civilization} / 特产：${world.resource}`));const row=document.createElement('div');row.className='locations';for(const location of locations){const area=document.createElement('section');area.className='location';const title=document.createElement('h3');title.textContent=location.name;const done=record.locations.includes(location.id),control=button(done?'已探索':location.action,()=>{if(!state.visited.includes(state.selected)){state.visited.push(state.selected);state.visited=state.visited.slice(-500);}if(record.locations.includes(location.id))return;record.locations.push(location.id);state.world[world.id]=record;collect(location.item);if(location.id==='moon')collect(world.resource);addLog(`${world.name} / ${location.name}：收集 ${location.item}`);eventMaybe();notify(`收集了 ${location.item}`);persist();beep();renderExplore();});control.disabled=done;area.append(title,p(location.text,'muted'),control);row.append(area);}article.append(row);const npc=document.createElement('section');npc.className='npc';npc.append(p(`${world.npc} / ${world.civilization}`));const text=record.choice==='share'?'你分享了信号，我们会为你留一盏灯。':record.choice==='keep'?'保留秘密也好。星际旅途需要自己的判断。':'旅人，你愿意把观测信号留给我们吗？';npc.append(p(text));if(!record.choice){for(const [choice,label]of [['share','分享信号'],['keep','保留信号']])npc.append(button(label,()=>{record.choice=choice;state.world[world.id]=record;if(choice==='share')collect('夜航邮票');addLog(`${world.name} / ${world.npc}：${label}`);notify('对话选择已记录。');persist();renderExplore();}));}if(record.locations.length===3&&record.choice)npc.append(p(`隐藏记录解锁：${world.hidden}。${record.choice==='share'?'你获得了一条文明之间的航线。':'你独自保留了它的坐标。'}`));else npc.append(p('探索三个地点并完成对话，可解锁这个星球的隐藏记录。','muted'));article.append(npc);$('inventory').textContent=Object.entries(state.inventory).map(([k,v])=>`${k} × ${v}`).join(' / ')||'背包还空着。去校准一根天线吧。';$('log').replaceChildren(...state.log.map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));}
function renderCompanion(){const c=tickCompanion(state.companion);$('stats').replaceChildren();for(const [key,label]of [['satiety','饱腹'],['mood','心情'],['energy','精力'],['affection','好感'],['growth','成长']]){const row=document.createElement('div');row.className='stat';const meter=document.createElement('progress');meter.max=100;meter.value=c[key];meter.setAttribute('aria-label',label);const number=document.createElement('span');number.textContent=Math.round(c[key]);row.append(p(label),meter,number);$('stats').append(row);}const memory=c.memories.at(-1);$('bird-dialogue').textContent=c.satiety<35?'咕……先聊花生，再聊宇宙。':c.energy<20?'翅膀低电量。让我蹲一会儿。':memory?`我记得${memory}。${c.affection>=20?'熟人待遇：允许你坐近一点。':'记性好，不代表我不挑剔。'}`:'地球人把休息叫浪费时间。嘎？';$('memories').replaceChildren(...(c.memories.length?c.memories.slice(-5):['还没有共同经历。']).map(x=>{const li=document.createElement('li');li.textContent=x;return li;}));persist();}
const game=createCombat($('arena'),text=>$('game-status').textContent=text,amount=>{state.wallet+=amount;persist();$('wallet').textContent=state.wallet;beep();});
function renderBoss(){currentBoss=boss($('boss-seed').value.trim()||daySeed());$('boss-seed').value=currentBoss.seed;game.configure(currentBoss);const errors=validateBoss(currentBoss),heuristic=survivalHeuristic(currentBoss);$('boss-details').replaceChildren(p(`${currentBoss.name} / ${currentBoss.archetype}`),p(`生命 ${currentBoss.health} · 两阶段 · 单次伤害 1 · ${currentBoss.bullets} 发/波 · 间隔 ${currentBoss.cooldown.toFixed(2)} 秒 · 奖励 ${currentBoss.reward}`,'muted'),p(`参数检查：${errors.length?'失败':'通过'} / 密度上限 ${heuristic.maxBulletsPerSecond} 发/秒 / 预警 0.65 秒`),p(heuristic.note,'muted'));$('start').disabled=errors.length>0;const review=state.reviews[currentBoss.seed];$('review-note').value=review?.note||'';$('review-status').textContent=`审核状态：${review?.status==='approved'?'本地已批准':review?.status==='rejected'?'本地已拒绝':'参数已检查，等待试玩审核'}。未发布。`;$('wallet').textContent=state.wallet;}
function setView(next){game.stop();view=next;for(const id of ['explore','companion','boss'])$(id).hidden=id!==next;for(const b of document.querySelectorAll('[data-view]'))b.setAttribute('aria-pressed',String(b.dataset.view===next));if(next==='companion')renderCompanion();if(next==='boss')renderBoss();}
for(const b of document.querySelectorAll('[data-view]'))b.addEventListener('click',()=>setView(b.dataset.view));for(const b of document.querySelectorAll('[data-care]'))b.addEventListener('click',()=>{if(interactCompanion(state.companion,b.dataset.care)){notify('灰鸟记住了这次互动。');beep();}else notify('精力不足，先让灰鸟休息。');renderCompanion();});$('next').onclick=()=>{state.sector++;state.selected=state.sector*6;persist();renderExplore();};$('previous').onclick=()=>{state.sector=Math.max(0,state.sector-1);state.selected=state.sector*6;persist();renderExplore();};$('apply-seed').onclick=()=>{const seed=$('seed').value.trim();if(!seed||seed===state.seed)return;if(!confirm('切换宇宙会清除当前探索记录和背包；伙伴、审核与试玩花生会保留。继续吗？'))return;state.seed=seed;state.sector=state.selected=0;state.world={};state.visited=[];state.inventory={};state.log=[];persist();renderExplore();};$('boss-seed').value=daySeed();$('generate').onclick=renderBoss;$('start').onclick=()=>{game.start();$('arena').focus();beep();};$('stop').onclick=()=>game.stop();for(const [id,status]of [['approve','approved'],['reject','rejected']])$(id).onclick=()=>{state.reviews[currentBoss.seed]={status,note:$('review-note').value.slice(0,160)};persist();renderBoss();};$('reset').onclick=()=>{if(!confirm('仅重置这个原型的探索、伙伴与 Boss 实验室进度。确定吗？'))return;game.stop();state=initialState();blocked=false;persist();renderExplore();if(view==='companion')renderCompanion();if(view==='boss')renderBoss();notify(blocked?'无法保存，重置仅作用于本次会话。':'原型进度已重置。');};$('sound').onclick=async()=>{try{audio??=new (window.AudioContext||window.webkitAudioContext)();await audio.resume();sound=!sound;$('sound').textContent=`声音：${sound?'开':'关'}`;$('sound').setAttribute('aria-pressed',String(sound));beep();}catch{notify('当前浏览器无法启用声音。');}};window.addEventListener('pagehide',()=>{tickCompanion(state.companion);persist();});renderExplore();notify(loaded.warning||'选一颗星球出发。进度只保存在这台浏览器。');

const requestedView=new URLSearchParams(location.search).get('view');if(['companion','boss'].includes(requestedView))setView(requestedView);
