export function createCombat(canvas,report,reward){
 const ctx=canvas.getContext('2d'),bird=new Image();bird.src='../assets/bird.webp';const art=new Image();let config,active=false,frame=0,last=0,elapsed=0,clock=0,player,enemy,shots=[],bullets=[],keys=new Set(),pointer=null,invulnerable=0,telegraph=0,targetX=300;
 const W=600,H=680;
 function status(text){report(text);}
 function stop(message='试玩已停止'){active=false;cancelAnimationFrame(frame);status(message);draw();}
 function configure(b){stop('候选已准备好，点击开始试玩。');config=b;player=null;enemy=null;art.src=`../assets/game/boss-${b.appearance}.webp`;art.onerror=()=>{art.onerror=null;art.src=`../assets/game/boss-${b.appearance}.svg`;};draw();}
 function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#101820';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#22303c';for(let y=20;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke();}if(!player||!enemy){ctx.fillStyle='#a6cbe3';ctx.font='22px Arial';ctx.textAlign='center';ctx.fillText('BOSS / 候选试玩',300,300);ctx.fillText('拖动灰鸟 · 自动射击',300,340);return;}if(art.complete&&art.naturalWidth)ctx.drawImage(art,enemy.x-45,55,90,90);else{ctx.fillStyle=`hsl(${config.hue} 35% 60%)`;ctx.fillRect(enemy.x-35,70,70,60);}ctx.fillStyle='#2a2e32';ctx.fillRect(80,20,440,8);ctx.fillStyle='#a6cbe3';ctx.fillRect(80,20,440*Math.max(0,enemy.hp)/config.health,8);if(telegraph>0){ctx.strokeStyle='#eeefed';ctx.setLineDash([8,12]);ctx.beginPath();ctx.moveTo(targetX,150);ctx.lineTo(targetX,H);ctx.stroke();ctx.setLineDash([]);}for(const s of shots){ctx.fillStyle='#a6cbe3';ctx.fillRect(s.x-2,s.y,4,14);}for(const b of bullets){ctx.fillStyle='#e3b079';ctx.beginPath();ctx.arc(b.x,b.y,6,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=invulnerable>0?.45:1;if(bird.complete&&bird.naturalWidth)ctx.drawImage(bird,player.x-24,player.y-24,48,48);ctx.globalAlpha=1;ctx.fillStyle='#eeefed';ctx.font='16px Arial';ctx.textAlign='left';ctx.fillText(`生命 ${player.hp}  /  阶段 ${enemy.hp<config.health/2?2:1}`,20,H-15);}
 function emit(){const r=config.speed,kind=config.archetype;for(let i=0;i<config.bullets;i++){if(kind==='扇形脉冲'){const angle=(i-(config.bullets-1)/2)*.32;bullets.push({x:enemy.x,y:145,vx:Math.sin(angle)*r,vy:Math.cos(angle)*r});}else if(kind==='交错星雨'){bullets.push({x:60+i*100+(Math.floor(elapsed)%2)*30,y:145,vx:0,vy:r});}else{const dx=targetX-enemy.x,dy=player.y-145,len=Math.hypot(dx,dy);bullets.push({x:enemy.x,y:145,vx:dx/len*r+(i-(config.bullets-1)/2)*16,vy:dy/len*r});}}}
 let fireClock=0;
 function loop(now){if(!active)return;const dt=Math.min(.04,(now-last)/1000||.016);last=now;elapsed+=dt;invulnerable=Math.max(0,invulnerable-dt);let mx=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0),my=(keys.has('ArrowDown')||keys.has('s')?1:0)-(keys.has('ArrowUp')||keys.has('w')?1:0);player.x=Math.max(24,Math.min(W-24,pointer?pointer.x:player.x+mx*260*dt));player.y=Math.max(200,Math.min(H-45,pointer?pointer.y:player.y+my*260*dt));enemy.x=300+Math.sin(elapsed*(enemy.hp<config.health/2?1.2:.7))*170;clock+=dt;if(clock>=config.cooldown&&telegraph<=0){clock=0;telegraph=.65;targetX=player.x;}if(telegraph>0){telegraph-=dt;if(telegraph<=0)emit();}fireClock+=dt;if(fireClock>=.18){fireClock=0;shots.push({x:player.x,y:player.y-25});}for(const s of shots){s.y-=420*dt;if(s.y<145&&s.y>55&&Math.abs(s.x-enemy.x)<45){enemy.hp-=6;s.y=-99;}}shots=shots.filter(s=>s.y>0);for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;if(invulnerable===0&&Math.hypot(b.x-player.x,b.y-player.y)<20){player.hp--;invulnerable=1.2;b.y=999;}}bullets=bullets.filter(b=>b.y<H+10&&b.x>-10&&b.x<W+10);draw();if(enemy.hp<=0){reward(config.reward);stop(`击败 ${config.name}，获得 ${config.reward} 本地试玩花生。`);return;}if(player.hp<=0){stop('本次试玩结束。可以重新挑战。');return;}if(elapsed>90){stop('90 秒试玩结束，未结算奖励。');return;}frame=requestAnimationFrame(loop);}
 function start(){if(!config)return;cancelAnimationFrame(frame);active=true;player={x:300,y:580,hp:3};enemy={x:300,hp:config.health};shots=[];bullets=[];pointer=null;clock=elapsed=fireClock=invulnerable=telegraph=0;keys.clear();last=performance.now();status('试玩中：拖动或方向键移动，自动射击。');frame=requestAnimationFrame(loop);}
 canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','w','a','s','d'].includes(e.key)){e.preventDefault();keys.add(e.key);}});canvas.addEventListener('keyup',e=>keys.delete(e.key));canvas.addEventListener('blur',()=>keys.clear());function move(e){const rect=canvas.getBoundingClientRect();pointer={x:(e.clientX-rect.left)/rect.width*W,y:(e.clientY-rect.top)/rect.height*H};}canvas.addEventListener('pointerdown',e=>{if(!active)return;canvas.focus();canvas.setPointerCapture(e.pointerId);move(e);});canvas.addEventListener('pointermove',e=>{if(canvas.hasPointerCapture(e.pointerId))move(e);});for(const event of ['pointerup','pointercancel'])canvas.addEventListener(event,()=>{pointer=null;});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)stop('页面隐藏，试玩已停止。');});return {configure,start,stop,isActive:()=>active};
}
