import {civilizations,biomes,resources,npcNames,bossArchetypes} from './data.mjs';
export function hash(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function rng(seed){let a=hash(seed);return()=>{a+=0x6D2B79F5;let t=Math.imul(a^a>>>15,1|a);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296;};}
export function planet(seed,index){const r=rng(`world-v1:${seed}:${index}`),pick=a=>a[Math.floor(r()*a.length)];return {id:String(index),name:`${pick(['咕','远','暮','微','寂','啾'])}${pick(['光','环','潮','雾','尘','翼'])} · ${index+1}`,biome:pick(biomes),civilization:pick(civilizations),resource:pick(resources),npc:pick(npcNames),hue:Math.floor(r()*360),hidden:pick(['废弃的信号井','埋在月壤里的花生契约','无人认领的星际航线','一张背面写着鸟语的地图'])};}
export function daySeed(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);}
export function boss(seed){const r=rng(`boss-v1:${seed}`);return {seed:String(seed),name:`${['弹窗','噪声','回声','广告'][Math.floor(r()*4)]}领主`,archetype:bossArchetypes[Math.floor(r()*3)],health:Math.floor(90+r()*61),damage:1,speed:65+r()*35,cooldown:1.05+r()*.65,bullets:3+Math.floor(r()*3),reward:12+Math.floor(r()*9),hue:Math.floor(r()*360),appearance:1+Math.floor(r()*9),phases:2};}
export function validateBoss(b){const errors=[];for(const k of ['health','damage','speed','cooldown','bullets','reward','hue'])if(!Number.isFinite(b[k]))errors.push(`${k}:invalid`);if(b.health<90||b.health>150)errors.push('health');if(b.damage!==1)errors.push('damage');if(b.cooldown<1.05||b.cooldown>1.7)errors.push('cooldown');if(b.bullets<3||b.bullets>5||b.bullets/b.cooldown>5)errors.push('density');if(b.speed<65||b.speed>100)errors.push('speed');if(b.reward<12||b.reward>20)errors.push('reward');if(!bossArchetypes.includes(b.archetype))errors.push('archetype');return errors;}
export function survivalHeuristic(b){return {passed:validateBoss(b).length===0&&b.speed<180&&b.bullets<6,maxBulletsPerSecond:+(b.bullets/b.cooldown).toFixed(2),minimumTelegraphSeconds:.65,note:'参数启发式，仅排除明显危险组合，不证明每场战斗都公平。'};}
export function initialState(){return {version:1,seed:'graybird',sector:0,selected:0,visited:[],inventory:{},world:{},log:[],lastEvent:0,companion:{satiety:70,mood:65,energy:80,affection:0,growth:0,lastTick:Date.now(),memories:[]},reviews:{},wallet:0};}
export function normalize(raw){const s=initialState();if(!raw||raw.version!==1)throw Error('Unsupported save');const n=(v,d,min=0,max=100)=>Number.isFinite(v)?Math.max(min,Math.min(max,v)):d;s.seed=typeof raw.seed==='string'?raw.seed.slice(0,60):s.seed;s.sector=n(raw.sector,0,0,1000000);s.selected=n(raw.selected,0,0,1000000);s.visited=Array.isArray(raw.visited)?raw.visited.filter(Number.isInteger).slice(-500):[];for(const [key,value] of Object.entries(raw.inventory||{}))if(resources.includes(key))s.inventory[key]=n(value,0,0,9999);s.world=Object.fromEntries(Object.entries(raw.world||{}).filter(([k,v])=>/^\d+$/.test(k)&&v&&typeof v==='object').slice(-500).map(([k,v])=>[k,{locations:Array.isArray(v.locations)?v.locations.filter(x=>['station','moon','outpost'].includes(x)):[],choice:['share','keep'].includes(v.choice)?v.choice:undefined}]));s.log=Array.isArray(raw.log)?raw.log.filter(x=>typeof x==='string').slice(-30):[];s.lastEvent=n(raw.lastEvent,0,0,Date.now());const c=raw.companion||{};for(const k of ['satiety','mood','energy','affection','growth'])s.companion[k]=n(c[k],s.companion[k]);s.companion.lastTick=n(c.lastTick,Date.now(),0,Date.now());s.companion.memories=Array.isArray(c.memories)?c.memories.filter(x=>typeof x==='string').slice(-12):[];s.reviews=Object.fromEntries(Object.entries(raw.reviews||{}).slice(-100).map(([k,v])=>[k,{status:['approved','rejected'].includes(v?.status)?v.status:'checked',note:typeof v?.note==='string'?v.note.slice(0,160):''}]));s.wallet=n(raw.wallet,0,0,99999);return s;}
export function tickCompanion(c,now=Date.now()){const hours=Math.max(0,Math.min(24,(now-c.lastTick)/3600000));c.satiety=Math.max(20,c.satiety-hours*2);c.mood=Math.max(30,c.mood-hours);c.energy=Math.min(100,c.energy+hours*3);c.lastTick=now;return c;}
export function interactCompanion(c,action){const cost={feed:0,rest:0,talk:3,play:10}[action];if(cost===undefined)return false;if(c.energy<cost)return false;c.energy-=cost;if(action==='feed')c.satiety=Math.min(100,c.satiety+18);if(action==='rest')c.energy=Math.min(100,c.energy+20);if(action==='talk')c.mood=Math.min(100,c.mood+8);if(action==='play')c.mood=Math.min(100,c.mood+12);c.affection=Math.min(100,c.affection+2);c.growth=Math.min(100,c.growth+1);c.memories.push({feed:'你带来的花生',rest:'你替我关掉的广播',talk:'一起听过的星际杂音',play:'那次差一点接住的流星'}[action]);c.memories=c.memories.slice(-12);return true;}
