const {chromium}=require('playwright'),chrome=require('@sparticuz/chromium').default,fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');const output=process.env.RESCUE_QA_OUTPUT||require('os').tmpdir();const server=http.createServer((req,res)=>{let f=path.join(root,decodeURI(req.url.split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);res.end();return}res.setHeader('content-type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));});
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));const b=await chromium.launch({executablePath:await chrome.executablePath(),args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'],headless:true});const results=[];
for(const width of [375,390,768,1280,1920]){const c=await b.newContext({viewport:{width,height:900},hasTouch:width<600,isMobile:width<600,reducedMotion:'reduce'});const p=await c.newPage(),errors=[],bad=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push(r.url())});await p.goto('http://127.0.0.1:8765/save-graybird/');await p.locator('#start').waitFor({state:'visible'});await p.waitForFunction(()=>!document.querySelector('#start').disabled);assert.equal(await p.locator('.cast-card').count(),8);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`${output}/game-title-${width}.png`});await p.locator('#start').click();await p.locator('#story-next').click();assert.equal(await p.evaluate(()=>rescueState.status),'playing');await p.locator('#pause').click();assert.equal(await p.evaluate(()=>rescueState.status),'paused');await p.locator('#resume').click();await p.locator('[data-character=mage]').click();assert.equal(await p.evaluate(()=>rescueState.character),'mage');await p.locator('#arena').focus();await p.keyboard.press('Space');assert((await p.evaluate(()=>rescueState.cooldown))>0);await p.screenshot({path:`${output}/game-scene-${width}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#pause').click();await p.locator('#quit').click();await p.locator('#continue').click();await p.locator('#story-next').click();assert.equal(await p.evaluate(()=>rescueState.chapter),0);assert.deepStrictEqual(errors,[]);assert.deepStrictEqual(bad,[]);results.push({width,crew:8,start:true,pause:true,ability:true,continue:true,overflow:false,errors,bad});await c.close();}
const c=await b.newContext({viewport:{width:390,height:900},hasTouch:true,isMobile:true});const p=await c.newPage();await p.goto('http://127.0.0.1:8765/save-graybird/');await p.waitForFunction(()=>!document.querySelector('#start').disabled);await p.clock.install();await p.locator('#start').click();await p.locator('#story-next').click();await p.locator('#game details summary').click();await p.locator('#assist').check();await p.locator('#game details summary').click();await p.locator('[data-character=mage]').click();const state=()=>p.evaluate(()=>rescueState);let loops=0;
async function step(ms=200){await p.clock.runFor(ms);++loops;}
async function move(x,y){for(let i=0;i<130;i++){let s=await state();if(['ready','won'].includes(s.status))return;if(s.status!=='playing')throw Error('unexpected '+JSON.stringify(s));const dx=x-s.player.x,dy=y-s.player.y;if(Math.hypot(dx,dy)<18)return;const key=Math.abs(dx)>Math.abs(dy)?(dx>0?'d':'a'):(dy>0?'s':'w');await p.keyboard.down(key);await step(Math.min(200,Math.max(40,Math.max(Math.abs(dx),Math.abs(dy))/170*1000)));await p.keyboard.up(key);if(s.cooldown<.1){await p.keyboard.press('8');if(s.chapter<5)await p.keyboard.press('4');await p.locator('#arena').focus();await p.keyboard.press('Space');}}throw Error('movement stuck '+JSON.stringify(await state()));}
async function next(){assert(await p.locator('#story').evaluate(d=>d.open));await p.locator('#story-next').click();await p.keyboard.press('4');}
await move(195,545);await move(195,120);await move(640,120);await move(690,150);await move(690,510);await move(610,510);await move(820,510);await move(820,85);await move(865,85);await step();await next();
await move(195,120);await move(660,120);await p.keyboard.press('e');await move(245,120);await p.keyboard.press('e');await move(705,120);await move(705,510);await p.keyboard.press('e');await step();await next();
await move(225,120);await p.keyboard.press('e');await move(705,120);await p.keyboard.press('e');await move(705,520);await p.keyboard.press('e');await step();await next();
await move(480,320);for(let i=0;i<45;i++){if((await state()).status!=='playing')break;const a=i*1.5;await move(480+Math.cos(a)*70,320+Math.sin(a)*70);}await step();await next();
for(const [x,y]of [[225,155],[730,170],[660,520]]){await move(x,y);await p.keyboard.press('e');}await step();await next();
await move(810,515);await p.keyboard.press('e');await move(865,85);await step(1500);await next();
for(const [x,y]of [[225,155],[730,170],[660,520]]){await move(x,y);await p.keyboard.press('e');}await move(480,320);for(let i=0;i<30;i++){if((await state()).status==='won')break;const a=i*1.5;try{await move(480+Math.cos(a)*70,320+Math.sin(a)*70)}catch(e){if((await state()).status!=='won')throw e;}}await step();assert.equal((await state()).status,'won');assert(await p.locator('#ending').isVisible());await p.screenshot({path:`${output}/game-ending-390.png`});console.log('FULL PLAYTHROUGH PASS',JSON.stringify(await state()));console.log(JSON.stringify(results));await c.close();await b.close();server.close();})().catch(e=>{console.error(e);server.close();process.exit(1)});
