// Generated by scripts/build_locales.py; do not edit.
'use strict';
// Original website field notes. These are not fetched posts or live X data.
const observations = [
 {subject:'internet',label:'INTERNET',title:window.GRAYBIRD_COPY["home.187"],body:window.GRAYBIRD_COPY["home.086"],aside:window.GRAYBIRD_COPY["home.087"]},
 {subject:'humans',label:'HUMANS',title:window.GRAYBIRD_COPY["home.188"],body:window.GRAYBIRD_COPY["home.189"],aside:window.GRAYBIRD_COPY["home.190"]},
 {subject:'ai',label:'ARTIFICIAL INTELLIGENCE',title:window.GRAYBIRD_COPY["home.191"],body:window.GRAYBIRD_COPY["home.192"],aside:window.GRAYBIRD_COPY["home.193"]},
 {subject:'life',label:'LIFE',title:window.GRAYBIRD_COPY["home.194"],body:window.GRAYBIRD_COPY["home.195"],aside:window.GRAYBIRD_COPY["home.196"]},
 {subject:'technology',label:'TECHNOLOGY',title:window.GRAYBIRD_COPY["home.197"],body:window.GRAYBIRD_COPY["home.198"],aside:window.GRAYBIRD_COPY["home.199"]},
 {subject:'curiosity',label:'CURIOSITY',title:window.GRAYBIRD_COPY["home.200"],body:window.GRAYBIRD_COPY["home.201"],aside:window.GRAYBIRD_COPY["home.202"]}
];
// The V2 records stay intact. Every channel now contains a second field note.
observations.push(
 {subject:'internet',label:'INTERNET',title:window.GRAYBIRD_COPY["home.203"],body:window.GRAYBIRD_COPY["home.204"],aside:window.GRAYBIRD_COPY["home.205"]},
 {subject:'humans',label:'HUMANS',title:window.GRAYBIRD_COPY["home.206"],body:window.GRAYBIRD_COPY["home.207"],aside:window.GRAYBIRD_COPY["home.208"]},
 {subject:'ai',label:'ARTIFICIAL INTELLIGENCE',title:window.GRAYBIRD_COPY["home.209"],body:window.GRAYBIRD_COPY["home.210"],aside:window.GRAYBIRD_COPY["home.211"]},
 {subject:'life',label:'LIFE',title:window.GRAYBIRD_COPY["home.212"],body:window.GRAYBIRD_COPY["home.213"],aside:window.GRAYBIRD_COPY["home.214"]},
 {subject:'technology',label:'TECHNOLOGY',title:window.GRAYBIRD_COPY["home.215"],body:window.GRAYBIRD_COPY["home.216"],aside:window.GRAYBIRD_COPY["home.217"]},
 {subject:'curiosity',label:'CURIOSITY',title:window.GRAYBIRD_COPY["home.218"],body:window.GRAYBIRD_COPY["home.219"],aside:window.GRAYBIRD_COPY["home.220"]}
);

const $ = selector => document.querySelector(selector);
const buttons = [...document.querySelectorAll('[data-subject]')];
const terminal = $('.terminal');
const record = $('#record');
const motion = matchMedia('(prefers-reduced-motion: reduce)');
const coarse = matchMedia('(pointer: coarse)');
let current = 0;
let pending = 0;
let scanTimer = 0;
let scanGeneration = 0;
const unfiled = {subject:'unfiled',label:'UNFILED',title:window.GRAYBIRD_COPY["home.221"],body:window.GRAYBIRD_COPY["home.222"],aside:window.GRAYBIRD_COPY["home.223"]};
let syncArtwork = () => {};

function renderRecord(index) {
 const note = index < 0 ? unfiled : observations[index];
 current = pending = index;
 buttons.forEach(button => button.setAttribute('aria-pressed', String(button.dataset.subject === note.subject)));
 $('#record-id').textContent = index < 0 ? 'OBSERVATION —' : `OBSERVATION ${String(index + 1).padStart(3, '0')}`;
 $('#record-subject').textContent = `SUBJECT: ${note.label}`;
 const title = $('#record-title');
 title.replaceChildren();
 note.title.split('\n').forEach((line, i) => { if (i) title.append(document.createElement('br')); title.append(document.createTextNode(line)); });
 $('#record-body').textContent = note.body;
 $('#record-aside').textContent = note.aside;
 const channel = observations.filter(item => item.subject === note.subject);
 const position = channel.indexOf(note) + 1;
 $('#record-count').textContent = index < 0 ? 'UNFILED / SIGNAL FOUND' : `${String(position).padStart(2, '0')} / ${String(channel.length).padStart(2, '0')} · ${note.subject.toUpperCase()}`;
 terminal.classList.remove('is-scanning');
 record.setAttribute('aria-busy', 'false');
 $('#request-status').textContent = window.GRAYBIRD_COPY["home.224"];
 syncArtwork(note.subject);
}

function selectRecord(index, updateUrl = true, scan = true) {
 if (index < -1 || index >= observations.length) return;
 clearTimeout(scanTimer);
 const generation = ++scanGeneration;
 pending = index;
 const note = index < 0 ? unfiled : observations[index];
 buttons.forEach(button => button.setAttribute('aria-pressed', String(button.dataset.subject === note.subject)));
 if (updateUrl) {
  const hash = index < 0 ? '#observation-unfiled' : `#observation-${String(index + 1).padStart(3, '0')}`;
  if (location.hash !== hash) history.pushState(null, '', hash);
 }
 $('#record-link').hidden = true;
 $('#share-record').textContent = window.GRAYBIRD_COPY["home.088"];
 if (!scan || motion.matches || document.hidden) { renderRecord(index); return; }
 terminal.classList.add('is-scanning');
 record.setAttribute('aria-busy', 'true');
 $('#request-status').textContent = window.GRAYBIRD_COPY["home.225"];
 scanTimer = setTimeout(() => { if (generation === scanGeneration) renderRecord(index); }, 140);
}

buttons.forEach(button => {
 button.setAttribute('aria-controls', 'record');
 button.addEventListener('click', () => selectRecord(observations.findIndex(note => note.subject === button.dataset.subject)));
 button.addEventListener('keydown', event => {
  const index = buttons.indexOf(button);
  let next;
  if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = (index + 1) % buttons.length;
  if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = (index + buttons.length - 1) % buttons.length;
  if (event.key === 'Home') next = 0;
  if (event.key === 'End') next = buttons.length - 1;
  if (next !== undefined) { event.preventDefault(); buttons[next].focus(); buttons[next].click(); }
 });
});
$('#next-record').addEventListener('click', () => {
 if (pending < 0) { selectRecord(0); return; }
 const channel = observations.map((note, index) => note.subject === observations[pending].subject ? index : -1).filter(index => index >= 0);
 selectRecord(channel[(channel.indexOf(pending) + 1) % channel.length]);
});

function readHash(scroll = true) {
 const hash = location.hash;
 let index = observations.findIndex((note, i) => hash === `#observation-${String(i + 1).padStart(3, '0')}`);
 if (index < 0) index = observations.findIndex(note => hash === `#observation-${note.subject}`);
 if (hash === '#observation-unfiled') index = -1;
 else if (index < 0) return;
 selectRecord(index, false, false);
 if (scroll) $('#terminal').scrollIntoView({behavior: 'instant'});
}
window.addEventListener('hashchange', () => readHash());
window.addEventListener('popstate', () => readHash());
$('#share-record').hidden = false;
$('#share-record').addEventListener('click', async () => {
 const hash = current < 0 ? '#observation-unfiled' : `#observation-${String(current + 1).padStart(3, '0')}`;
 const url = new URL(hash, location.href).href;
 try {
  if (!navigator.clipboard) throw new Error('Clipboard unavailable');
  await navigator.clipboard.writeText(url);
  $('#share-record').textContent = window.GRAYBIRD_COPY["home.226"];
 } catch {
  const input = $('#record-link'); input.hidden = false; input.value = url; input.focus(); input.select();
  $('#share-record').textContent = window.GRAYBIRD_COPY["home.227"];
 }
});
readHash();

const whispers = [
 window.GRAYBIRD_COPY["home.228"],
 window.GRAYBIRD_COPY["home.229"],
 window.GRAYBIRD_COPY["home.230"],
 window.GRAYBIRD_COPY["home.231"],
 window.GRAYBIRD_COPY["home.232"],
 window.GRAYBIRD_COPY["home.233"]
];
let contactCount = 0;
let previousWhisper = -1;
let reactionTimer = 0;
const hero = $('.hero');
const portrait = $('.portrait-contact');
function contactBird(source) {
 contactCount++;
 let index = Math.floor(Math.random() * whispers.length);
 if (index === previousWhisper) index = (index + 1) % whispers.length;
 previousWhisper = index;
 let line = whispers[index];
 if (contactCount >= 4 && contactCount < 8) line = window.GRAYBIRD_COPY["home.234"];
 if (contactCount >= 8) line = window.GRAYBIRD_COPY["home.235"];
 const output = source === 'portrait' ? $('#portrait-message') : $('#bird-message');
 output.textContent = line;
 hero.classList.add('is-observed'); portrait.classList.add('is-observed');
 clearTimeout(reactionTimer);
 reactionTimer = setTimeout(() => { hero.classList.remove('is-observed'); portrait.classList.remove('is-observed'); }, 600);
 if (contactCount === 11) { selectRecord(-1); $('#terminal').scrollIntoView({behavior: motion.matches ? 'instant' : 'smooth'}); }
}
$('#scene-bird').addEventListener('click', () => contactBird('scene'));
portrait.disabled = false;
portrait.addEventListener('click', () => contactBird('portrait'));
$('#bird-note').addEventListener('click', () => {
 const line = $('#aside-message'); line.textContent = line.textContent.trim() ? '' : window.GRAYBIRD_COPY["home.236"];
});

function updateClock() { $('#clock').textContent = `EARTH TIME / ${new Date().toISOString().slice(11, 16)} UTC`; }
let clockTimer = 0;
function resumeClock() { clearInterval(clockTimer); if (!document.hidden) { updateClock(); clockTimer = setInterval(updateClock, 60000); } }
resumeClock();

// One scheduled frame per input event, no continuous JS animation loop.
let frame = 0;
let heroVisible = true;
let px = 0;
let py = 0;
let heroTop = 0;
let heroHeight = 1;
let scrolling = 0;
const picture = $('.hero-art');
const sceneImage = picture.querySelector('img');
let layers = [];
function scheduleScene() {
 if (heroVisible && !frame && !document.hidden && !motion.matches) frame = requestAnimationFrame(drawScene);
}
function drawScene() {
 frame = 0;
 if (!heroVisible || motion.matches || document.hidden) return;
 const progress = Math.max(0, Math.min(1, (scrollY - heroTop) / heroHeight));
 const strength = coarse.matches ? 0.45 : 1;
 hero.style.setProperty('--camera-x', `${px * 5 * strength}px`);
 hero.style.setProperty('--camera-y', `${py * 3 * strength + progress * 24 * strength}px`);
 hero.style.setProperty('--camera-scale', String(1 + progress * (coarse.matches ? 0.012 : 0.035)));
 hero.style.setProperty('--star-x', `${px * -8 * strength}px`);
 hero.style.setProperty('--star-y', `${py * -5 * strength + progress * -18 * strength}px`);
 hero.style.setProperty('--bird-x', `${px * 3 * strength}px`);
 hero.style.setProperty('--bird-y', `${py * 2 * strength}px`);
 hero.style.setProperty('--title-y', `${progress * -65}px`);
 hero.style.setProperty('--title-opacity', String(Math.max(0, 1 - progress * 1.8)));
}

function measureScene() {
 const box = hero.getBoundingClientRect();
 heroTop = box.top + scrollY; heroHeight = box.height;
 const mobile = matchMedia('(max-width:600px)').matches;
 const iw = mobile ? 960 : 1536; const ih = mobile ? 720 : 576;
 const scale = Math.max(box.width / iw, box.height / ih);
 const posX = mobile ? 0.2 : 0.5;
 const posY = mobile ? 1 : box.width >= 1800 ? 0.62 : 0.65;
 const ox = (box.width - iw * scale) * posX; const oy = (box.height - ih * scale) * posY;
 const bird = mobile ? [130, 340, 220, 270] : [400, 260, 190, 220];
 const x = bird[0] * scale + ox; const y = bird[1] * scale + oy;
 const target = $('#scene-bird');
 const width = Math.max(44, Math.min(bird[2] * scale, box.width - Math.max(8, x) - 8));
 target.style.left = `${Math.max(8, x)}px`; target.style.top = `${Math.max(8, y)}px`;
 target.style.width = `${width}px`; target.style.height = `${Math.max(44, bird[3] * scale)}px`;
 target.hidden = false;
 hero.style.setProperty('--bird-center-x', `${x + bird[2] * scale / 2}px`);
 hero.style.setProperty('--bird-center-y', `${y + bird[3] * scale / 2}px`);
 hero.style.setProperty('--bird-radius-x', `${bird[2] * scale * 0.65}px`);
 hero.style.setProperty('--bird-radius-y', `${bird[3] * scale * 0.65}px`);
 scheduleScene();
}
if (CSS.supports('mask-image', 'radial-gradient(black, transparent)')) {
 for (const name of ['bird', 'foreground']) {
  const clone = picture.cloneNode(true); clone.className = `scene-layer scene-${name}`;
  clone.setAttribute('aria-hidden', 'true'); clone.querySelector('img').alt = '';
  clone.querySelector('img').removeAttribute('fetchpriority'); hero.prepend(clone); layers.push(clone);
 }
}
sceneImage.addEventListener('load', measureScene);
measureScene();
document.documentElement.classList.add('system-connected');
hero.addEventListener('pointermove', event => {
 if (motion.matches || !heroVisible) return;
 if (event.pointerType === 'touch') return;
 const box = hero.getBoundingClientRect();
 px = Math.max(-1, Math.min(1, (event.clientX - box.left) / box.width * 2 - 1));
 py = Math.max(-1, Math.min(1, (event.clientY - box.top) / box.height * 2 - 1)); scheduleScene();
});
hero.addEventListener('pointerleave', () => { px = py = 0; scheduleScene(); });
hero.addEventListener('touchstart', event => {
 if (motion.matches) return;
 px = (event.touches[0].clientX / innerWidth - 0.5) * 0.6; scheduleScene();
}, {passive: true});
hero.addEventListener('touchend', () => { px = py = 0; scheduleScene(); }, {passive: true});
window.addEventListener('scroll', () => { scheduleScene(); }, {passive: true});
window.addEventListener('resize', () => { cancelAnimationFrame(scrolling); scrolling = requestAnimationFrame(measureScene); }, {passive: true});

const sections = [...document.querySelectorAll('main > section')];
const phases = ['01 / ARRIVAL', '02 / OBSERVATION', '03 / DATABASE', '04 / TRANSMISSION', '05 / PROJECT'];
const distances = [window.GRAYBIRD_COPY["home.031"], window.GRAYBIRD_COPY["home.237"], window.GRAYBIRD_COPY["home.238"], window.GRAYBIRD_COPY["home.239"], window.GRAYBIRD_COPY["home.240"]];
let sectionFrame = 0;
let lastPhase = -1;
function updatePhase() {
 sectionFrame = 0;
 let index = 0;
 sections.forEach((section, i) => { if (section.getBoundingClientRect().top <= innerHeight * 0.5) index = i; });
 if (index === lastPhase) return;
 lastPhase = index;
 $('#system-phase').textContent = phases[index]; $('#system-distance').textContent = distances[index];
 document.body.dataset.phase = String(index + 1);
 document.documentElement.style.setProperty('--system-progress', String((index + 1) / sections.length));
}
window.addEventListener('scroll', () => {
 if (!sectionFrame && !document.hidden) sectionFrame = requestAnimationFrame(updatePhase);
}, {passive: true});
updatePhase();
if ('IntersectionObserver' in window) {
 const sceneObserver = new IntersectionObserver(entries => {
  heroVisible = entries[0].isIntersecting;
  hero.classList.toggle('scene-active', heroVisible && !document.hidden && !motion.matches);
  if (heroVisible) scheduleScene();
 }, {threshold: 0});
 sceneObserver.observe(hero);
 const revealObserver = new IntersectionObserver(entries => {
  entries.forEach(entry => {
   if (entry.isIntersecting) { entry.target.classList.add('is-entered'); revealObserver.unobserve(entry.target); }
  });
 }, {threshold: 0.06});
 sections.slice(1).forEach(section => { section.classList.add('system-depth'); revealObserver.observe(section); });
} else hero.classList.add('scene-active');

function pauseOrResume() {
 document.documentElement.classList.toggle('system-paused', document.hidden);
 hero.classList.toggle('scene-active', heroVisible && !document.hidden && !motion.matches);
 resumeClock();
 if (document.hidden || motion.matches) {
  cancelAnimationFrame(frame); frame = 0;
  cancelAnimationFrame(sectionFrame); sectionFrame = 0;
  clearTimeout(scanTimer); if (record.getAttribute('aria-busy') === 'true') renderRecord(pending);
 } else { scheduleScene(); updatePhase(); }
 if (motion.matches) {
  ['--camera-x', '--camera-y', '--camera-scale', '--star-x', '--star-y', '--bird-x', '--bird-y', '--title-y', '--title-opacity'].forEach(name => hero.style.removeProperty(name));
 }
}
document.addEventListener('visibilitychange', pauseOrResume);
if (motion.addEventListener) motion.addEventListener('change', pauseOrResume);
else if (motion.addListener) motion.addListener(pauseOrResume);

// The supplied artwork is kept byte-for-byte, below the fold and lazy loaded.
const archive = $('#visual-archive');
const artFrames = [...archive.querySelectorAll('.archive-frame')];
const artButtons = [...archive.querySelectorAll('[data-art-index]')];
const artDialog = $('#art-dialog');
let activeArt = 0;
let scrollArchiveMode = false;
function showArtwork(index) {
 activeArt = (index + artFrames.length) % artFrames.length;
 artFrames.forEach((figure, i) => { figure.hidden = !scrollArchiveMode && i !== activeArt; figure.classList.toggle('is-current', i === activeArt); });
 artButtons.forEach((button, i) => button.setAttribute('aria-pressed', String(i === activeArt)));
 if (!scrollArchiveMode) $('#art-count').textContent = `${String(activeArt + 1).padStart(2, '0')} / ${String(artFrames.length).padStart(2, '0')}`;
}
function chooseArtwork(index) {
 showArtwork(index);
 if (scrollArchiveMode) artFrames[activeArt].scrollIntoView({block: 'center', behavior: motion.matches ? 'instant' : 'smooth'});
 const subject = artFrames[activeArt].dataset.artSubject;
 if (pending < 0 || observations[pending].subject !== subject) {
  selectRecord(observations.findIndex(note => note.subject === subject), true, false);
  showArtwork(index);
 }
}
artButtons.forEach((button, index) => {
 button.addEventListener('click', () => chooseArtwork(index));
 button.addEventListener('keydown', event => {
  let next;
  if (event.key === 'ArrowRight' || event.key === 'ArrowDown') next = (index + 1) % artButtons.length;
  if (event.key === 'ArrowLeft' || event.key === 'ArrowUp') next = (index + artButtons.length - 1) % artButtons.length;
  if (event.key === 'Home') next = 0;
  if (event.key === 'End') next = artButtons.length - 1;
  if (next !== undefined) { event.preventDefault(); artButtons[next].focus(); chooseArtwork(next); }
 });
});
$('#previous-art').addEventListener('click', () => chooseArtwork(activeArt - 1));
$('#next-art').addEventListener('click', () => chooseArtwork(activeArt + 1));
syncArtwork = subject => {
 const mapped = subject === 'technology' ? 'internet' : subject;
 const index = artFrames.findIndex(figure => figure.dataset.artSubject === mapped);
 if (index >= 0) showArtwork(index);
};
archive.classList.add('is-interactive');
archive.querySelector('.archive-index').hidden = false;
archive.querySelector('.archive-controls').hidden = false;
showArtwork(0);
syncArtwork(current < 0 ? 'unfiled' : observations[current].subject);

artFrames.forEach(figure => {
 const link = figure.querySelector('.archive-image');
 if (typeof artDialog.showModal !== 'function') return; // Keep the original link fallback.
 link.setAttribute('aria-haspopup', 'dialog');
 link.setAttribute('aria-label', `${window.GRAYBIRD_COPY.viewPrefix}${figure.querySelector('h4').textContent}${window.GRAYBIRD_COPY.viewSuffix}`);
 link.addEventListener('click', event => {
  if (event.ctrlKey || event.metaKey || event.shiftKey || event.altKey) return;
  event.preventDefault();
  const image = figure.querySelector('img');
  $('#art-dialog-image').src = image.getAttribute('src');
  $('#art-dialog-image').alt = image.alt;
  $('#art-dialog-image').width = image.width;
  $('#art-dialog-image').height = image.height;
  $('#art-dialog-title').textContent = figure.querySelector('.archive-coordinate').textContent;
  $('#art-dialog-note').textContent = figure.querySelector('h4').textContent;
  artDialog.showModal();
  document.body.classList.add('art-open');
 });
});
$('#close-art').addEventListener('click', () => artDialog.close());
artDialog.addEventListener('close', () => document.body.classList.remove('art-open'));
artDialog.addEventListener('click', event => {
 if (event.target !== artDialog) return;
 const box = artDialog.getBoundingClientRect();
 if (event.clientX < box.left || event.clientX > box.right || event.clientY < box.top || event.clientY > box.bottom) artDialog.close();
});

// Small pointer feedback; existing text, events and scene transforms stay intact.
(() => {
 const finePointer = matchMedia('(hover:hover) and (pointer:fine)');
 const targets = [...document.querySelectorAll('.portrait-contact,.enter')];
 let queued = 0, current = null, x = 0, y = 0;
 function reset() {
  cancelAnimationFrame(queued); queued = 0;
  targets.forEach(el => { el.style.removeProperty('--magnet-x'); el.style.removeProperty('--magnet-y'); });
  current = null;
 }
 targets.forEach(el => {
  el.addEventListener('pointermove', event => {
   if (motion.matches || !finePointer.matches || document.hidden || event.pointerType === 'touch') return;
   const box = el.getBoundingClientRect();
   current = el;
   x = Math.max(-4, Math.min(4, (event.clientX - box.left - box.width / 2) * .035));
   y = Math.max(-3, Math.min(3, (event.clientY - box.top - box.height / 2) * .035));
   if (!queued) queued = requestAnimationFrame(() => {
    queued = 0;
    if (!current) return;
    current.style.setProperty('--magnet-x', `${x}px`);
    current.style.setProperty('--magnet-y', `${y}px`);
   });
  }, {passive:true});
  el.addEventListener('pointerleave', reset);
  el.addEventListener('blur', reset);
 });
 document.addEventListener('visibilitychange', reset);
 motion.addEventListener('change', reset);
 finePointer.addEventListener('change', reset);
})();
