import {RescueGame,CHAPTERS,WORLD} from './engine.js';
const $=s=>document.querySelector(s),canvas=$('#arena'),ctx=canvas.getContext('2d');
const KEY='graybird-rescue-progress-v1',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let characters=[],sprites={},backgrounds={},game=new RescueGame(),last=0,loaded=false,seenStatus='',audio=null,sound=false,saveTick=0,drag=null,held=new Set(),keys=new Set(),saving=true;
const safeRead=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch{return null;}};
const saved=safeRead();const validSave=saved&&Number.isInteger(saved.chapter)&&saved.chapter>=0&&saved.chapter<7&&typeof saved.total==='number'&&Number.isFinite(saved.total)&&saved.total>=0;
function save(){try{localStorage.setItem(KEY,JSON.stringify({chapter:game.chapter,total:game.total,retries:game.retries,assist:game.assist,completed:game.completed}));}catch{saving=false;}}
function ping(freq=440){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});const o=audio.createOscillator(),gain=audio.createGain();o.type='sine';o.frequency.value=freq;gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.14);}catch{sound=false;$('#sound').textContent='声音不可用';}}
function clearInput(){keys.clear();held.clear();drag=null;document.querySelectorAll('.dpad button').forEach(b=>b.classList.remove('held'));}
function portrait(c){const img=document.createElement('img');img.className='portrait';img.src=sprites[c.id].toDataURL();img.alt=c.name;return img;}
function makeSprite(image,crop){const [x,y,w,h]=crop.map((n,i)=>n*(i%2?image.height:image.width));const off=document.createElement('canvas');off.width=Math.round(w);off.height=Math.round(h);const c=off.getContext('2d',{willReadFrequently:true});c.drawImage(image,x,y,w,h,0,0,off.width,off.height);
 // Remove only boundary-connected neutral backdrop while rendering the supplied mother sheet.
 // Inner white eye/armor details are never used as fill seeds.
 const im=c.getImageData(0,0,off.width,off.height),d=im.data,W=off.width,H=off.height,seen=new Uint8Array(W*H),queue=new Int32Array(W*H);let head=0,tail=0;
 const bg=[d[0],d[1],d[2]],threshold=bg[0]>220?60:45;
 const neutral=i=>{const j=i*4;return Math.max(d[j],d[j+1],d[j+2])-Math.min(d[j],d[j+1],d[j+2])<24&&Math.hypot(d[j]-bg[0],d[j+1]-bg[1],d[j+2]-bg[2])<threshold;};
 const seed=i=>{if(!seen[i]&&neutral(i)){seen[i]=1;queue[tail++]=i;}};for(let i=0;i<W;i++){seed(i);seed((H-1)*W+i);}for(let y=0;y<H;y++){seed(y*W);seed(y*W+W-1);}while(head<tail){const i=queue[head++];d[i*4+3]=0;const x=i%W,y=Math.floor(i/W);if(x)seed(i-1);if(x<W-1)seed(i+1);if(y)seed(i-W);if(y<H-1)seed(i+W);}c.putImageData(im,0,0);return off;
}
async function loadImage(src){const im=new Image();im.src=src;await im.decode();return im;}
async function boot(){try{const response=await fetch('characters.json');if(!response.ok)throw Error('角色资料无法读取');characters=await response.json();await Promise.all(characters.map(async c=>{const im=await loadImage(c.image);sprites[c.id]=makeSprite(im,c.crop);}));await Promise.all([...new Set([...CHAPTERS.map(x=>x.art),'/assets/rescue/07-afterglow.webp'])].map(async src=>backgrounds[src]=await loadImage(src)));
 loaded=true;$('#start').disabled=false;$('#start').textContent='出发，把它带回来 →';$('#load-status').textContent='角色与信号就绪。无需登录，进度只保存在这台设备。';if(validSave&&!saved.completed)$('#continue').hidden=false;
 const cast=$('#cast-list'),roster=$('#roster');characters.forEach((c,i)=>{const card=document.createElement('article');card.className='cast-card';card.append(portrait(c));const h=document.createElement('h3');h.textContent=c.name;const p=document.createElement('p');p.textContent=c.id==='graybird'?'获救后加入 · 信号反击':c.skill+' · '+c.description;card.append(h,p);cast.append(card);const b=document.createElement('button');b.dataset.character=c.id;b.setAttribute('aria-pressed','false');b.append(portrait(c));const s=document.createElement('span');s.textContent=c.name;b.append(s);b.title=`${i+1} · ${c.skill}`;b.onclick=()=>{game.select(c.id);ping(350);updateHud();};roster.append(b);});
 requestAnimationFrame(frame);
 }catch(e){$('#load-status').textContent='部分角色或漫画未能加载，请刷新重试。也可以先去原作画廊。';$('#start').textContent='加载失败，请刷新';console.error(e);}}
function resize(){const mobile=innerWidth<600;canvas.width=mobile?640:960;canvas.height=mobile?700:640;}
resize();addEventListener('resize',resize);
function showStory(){clearInput();const c=CHAPTERS[game.chapter];$('#story-art').src=c.art;$('#story-art').alt=c.title+'原作场景';$('#story-no').textContent=`ACT ${String(game.chapter+1).padStart(2,'0')} / 07 · ${c.subtitle}`;$('#story-title').textContent=c.title;$('#story-text').textContent=c.text;$('#story-goal').textContent='本幕目标：'+c.goal;$('#story').showModal();updateHud();render();}
function begin(resume=false){if(!loaded)return;game=new RescueGame({assist:resume&&validSave?!!saved.assist:$('#assist').checked});if(resume&&validSave){game.total=saved.total;game.retries=Math.max(0,Number(saved.retries)||0);game.setup(saved.chapter);}$('#assist').checked=game.assist;$('#landing').hidden=true;$('#ending').hidden=true;$('#game').hidden=false;seenStatus='ready';save();$('#game').scrollIntoView({block:'start'});showStory();}
$('#start').onclick=()=>begin();$('#continue').onclick=()=>begin(true);$('#replay').onclick=()=>begin();
$('#story-next').onclick=()=>{$('#story').close();game.start();seenStatus='playing';canvas.focus({preventScroll:true});save();ping(550);};$('#story').addEventListener('cancel',e=>e.preventDefault());
function pause(){if(game.status!=='playing')return;game.pause();clearInput();save();$('#pause-dialog').showModal();updateHud();}
$('#pause').onclick=pause;$('#resume').onclick=()=>{$('#pause-dialog').close();game.resume();last=0;canvas.focus({preventScroll:true});};$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();$('#resume').click();});
function home(){for(const d of document.querySelectorAll('dialog'))if(d.open)d.close();game.pause();clearInput();save();$('#game').hidden=true;$('#ending').hidden=true;$('#landing').hidden=false;$('#continue').hidden=game.completed;$('#continue').onclick=()=>{game.setup(game.chapter);$('#landing').hidden=true;$('#game').hidden=false;showStory();};}
$('#quit').onclick=home;$('#failure-home').onclick=home;$('#retry').onclick=()=>{$('#failure').close();game.setup(game.chapter);seenStatus='ready';save();showStory();};$('#failure').addEventListener('cancel',e=>e.preventDefault());
$('#interact').onclick=()=>{if(game.interact())ping(660);};$('#ability').onclick=()=>{if(game.ability())ping(300);};$('#assist').onchange=e=>{game.assist=e.target.checked;save();};
$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='声音：'+(sound?'开':'关');$('#sound').setAttribute('aria-pressed',String(sound));if(sound)ping();else if(audio)audio.suspend().catch(()=>{});};
function updateHud(){const c=CHAPTERS[game.chapter],ch=characters.find(c=>c.id===game.character);$('#chapter-label').textContent=`ACT ${String(game.chapter+1).padStart(2,'0')} / 07 · ${c.subtitle}`;$('#mission-name').textContent=c.title;$('#health').textContent='生命 '+('●'.repeat(Math.max(0,game.hp)))+('○'.repeat(5-Math.max(0,game.hp)));$('#health').setAttribute('aria-label',`生命 ${game.hp} / 5`);
 let goal=c.goal;if(game.mode==='collect')goal='信号碎片 '+game.items.filter(x=>x.done).length+' / 3';else if(game.mode==='sequence')goal='接入 '+game.sequence+' / 3 · 月→星→日';else if(game.mode==='hold')goal='零点信号 '+Math.floor(game.progress)+' / 24 秒';else if(game.mode==='finale')goal='屏障 '+game.nodes.filter(n=>n.done).length+'/3 · 舰队信号 '+game.bossHp;else goal='装置 '+game.nodes.filter(n=>n.done).length+' / '+game.nodes.length;$('#goal').textContent=goal;$('#alarm').textContent=game.chapter<3?'警戒 '+Math.floor(game.alarm)+'%':'护盾 '+(game.shield>0?game.shield.toFixed(1)+'s':'待命')+(game.assist?' · 故事模式':'');$('#active-character').textContent=ch?ch.name+' · '+ch.skill:'';$('#ability').textContent=game.cooldown>0?`冷却 ${Math.ceil(game.cooldown)}s`:(ch?ch.skill:'能力');$('#ability').disabled=game.cooldown>0;$('#scene-help').textContent=c.help;$('#toast').textContent=game.messageTime>0?game.message:'';document.querySelectorAll('[data-character]').forEach(b=>{b.disabled=b.dataset.character==='graybird'&&game.chapter<5;b.setAttribute('aria-pressed',String(b.dataset.character===game.character));});}
const moveKeys=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D']);
addEventListener('keydown',e=>{if($('#game').hidden||document.querySelector('dialog[open]')||e.target.matches('input,textarea,summary'))return;if(moveKeys.has(e.key)){e.preventDefault();keys.add(e.key.toLowerCase());}if(e.repeat)return;if(e.key===' '&&e.target===canvas){e.preventDefault();$('#ability').click();}if(e.key.toLowerCase()==='e')$('#interact').click();if(e.key.toLowerCase()==='p'){e.preventDefault();pause();}if(/^[1-8]$/.test(e.key)){const c=characters[Number(e.key)-1];if(c)game.select(c.id);}});
addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{clearInput();if(game.status==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(game.status==='playing')pause();if(audio)audio.suspend().catch(()=>{});}});
document.querySelectorAll('.dpad button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(game.status!=='playing')return;b.setPointerCapture(e.pointerId);held.add(b.dataset.dir);b.classList.add('held');};const end=()=>{held.delete(b.dataset.dir);b.classList.remove('held');};b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end;});
canvas.onpointerdown=e=>{if(game.status!=='playing')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,dx:0,dy:0};canvas.focus({preventScroll:true});};canvas.onpointermove=e=>{if(!drag)return;drag.dx=e.clientX-drag.x;drag.dy=e.clientY-drag.y;};const release=()=>drag=null;canvas.onpointerup=release;canvas.onpointercancel=release;canvas.onlostpointercapture=release;
function input(){let x=(keys.has('arrowright')||keys.has('d')||held.has('right')?1:0)-(keys.has('arrowleft')||keys.has('a')||held.has('left')?1:0),y=(keys.has('arrowdown')||keys.has('s')||held.has('down')?1:0)-(keys.has('arrowup')||keys.has('w')||held.has('up')?1:0);if(drag&&Math.hypot(drag.dx,drag.dy)>10){x=drag.dx;y=drag.dy;}return{x,y};}
function won(){clearInput();save();$('#game').hidden=true;$('#ending').hidden=false;$('#result').textContent=`你和伙伴们完成了七幕营救。用时 ${Math.floor(game.total/60)} 分 ${Math.floor(game.total%60)} 秒 · 重试 ${game.retries} 次${game.assist?' · 故事模式':''}。`;$('#ending').scrollIntoView({behavior:'auto',block:'start'});ping(720);}
$('#copy-card').onclick=async()=>{const text=`我和伙伴们把灰鸟救出来了 🐦‍⬛\n《拯救小灰鸟》七幕通关 · ${Math.floor(game.total/60)}分${Math.floor(game.total%60)}秒\nhttps://graybird.space/save-graybird/`;try{await navigator.clipboard.writeText(text);$('#copy-status').textContent='营救纪念卡已复制。';}catch{$('#copy-status').textContent=text;}};
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(loaded&&!$('#game').hidden){game.step(dt,input());saveTick+=dt;if(saveTick>3&&game.status==='playing'){saveTick=0;save();}if(game.status!==seenStatus){seenStatus=game.status;if(game.status==='chapter-complete'){save();game.setup(game.chapter+1);seenStatus='ready';save();showStory();ping(700);}else if(game.status==='failed'){clearInput();save();$('#failure').showModal();}else if(game.status==='won')won();}updateHud();render();}requestAnimationFrame(frame);}
function cover(im,x,y,w,h,alpha=1){if(!im)return;const r=Math.max(w/im.width,h/im.height);ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x+(w-im.width*r)/2,y+(h-im.height*r)/2,im.width*r,im.height*r);ctx.restore();}
function text(s,x,y,size=13,color='#c1ced7'){ctx.font=`${size}px Arial,"Noto Sans CJK SC",sans-serif`;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(s,x,y);}
function circle(x,y,r,color,stroke=false){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx[stroke?'strokeStyle':'fillStyle']=color;if(stroke){ctx.lineWidth=2;ctx.stroke();}else ctx.fill();}
function sprite(id,x,y,size=62){const im=sprites[id];if(!im)return;const h=size,w=h*im.width/im.height;ctx.drawImage(im,x-w/2,y-h+16,w,h);}
function render(){const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);ctx.fillStyle='#0b121b';ctx.fillRect(0,0,W,H);const camX=W<WORLD.w?Math.max(0,Math.min(WORLD.w-W,game.player.x-W/2)):0,camY=H<WORLD.h?Math.max(0,Math.min(WORLD.h-H,game.player.y-H/2)):-(H-WORLD.h)/2;
 ctx.save();ctx.translate(-camX,-camY);cover(backgrounds[CHAPTERS[game.chapter].art],0,0,960,640,.18);ctx.fillStyle='#0a1521a8';ctx.fillRect(0,0,960,640);
 ctx.strokeStyle='#b4c3d00d';ctx.lineWidth=1;for(let x=0;x<960;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.stroke();}for(let y=0;y<640;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(960,y);ctx.stroke();}
 ctx.strokeStyle='#637d9350';ctx.strokeRect(24,25,912,590);text(game.chapter<5?'封锁区 / KEEP THE SIGNAL ALIVE':'撤离区 / BRING OUR FRIEND HOME',480,55,11,'#8ba1b5');
 for(const r of game.walls){ctx.fillStyle='#202d39';ctx.fillRect(r.x,r.y,r.w,r.h);ctx.strokeStyle='#708595';ctx.strokeRect(r.x,r.y,r.w,r.h);for(let x=r.x+10;x<r.x+r.w;x+=18){ctx.fillStyle='#52606b';ctx.fillRect(x,r.y+4,5,3);}}
 const exitReady=game.mode==='collect'?game.items.every(i=>i.done):game.mode==='escort'&&game.nodes[0].done;
 if(['collect','escort'].includes(game.mode)){ctx.fillStyle=exitReady?'#95c9b32e':'#333d4840';ctx.fillRect(827,47,76,76);ctx.strokeStyle=exitReady?'#b2ebc9':'#617384';ctx.strokeRect(827,47,76,76);text(exitReady?'出口 ↑':'入口',865,93,15,exitReady?'#b2ebc9':'#8794a2');}
 if(game.mode==='hold'||game.mode==='finale'){circle(480,320,145,game.mode==='hold'?'#f0bb7330':'#ad9be930');circle(480,320,145,game.mode==='hold'?'#e8b77c':'#a8a0ed',true);circle(480,320,46,'#bccbd420');text(game.mode==='hold'?'稳定信号':'屏障信号阵',480,315,17);text(game.mode==='hold'?Math.floor(game.progress)+' / 24s':'舰队信号 '+game.bossHp,480,341,13,'#edc486');}
 if(game.mode==='collect')for(const n of game.items)if(!n.done){ctx.save();ctx.translate(n.x,n.y);ctx.rotate(Math.PI/4);ctx.fillStyle='#a6cbe3';ctx.fillRect(-9,-9,18,18);ctx.restore();circle(n.x,n.y,28,'#a6cbe340',true);}
 if(game.mode!=='collect'&&game.mode!=='hold')for(const n of game.nodes){circle(n.x,n.y,35,n.done?'#9ce4bc30':'#e8b77c25');circle(n.x,n.y,28,n.done?'#9ce4bc':'#e8b77c',true);ctx.fillStyle=n.done?'#b5e8ca':'#e8b77c';ctx.fillRect(n.x-10,n.y-10,20,20);text(n.done?'已接通':n.label,n.x,n.y+52,13,n.done?'#b5e8ca':'#e8b77c');}
 for(const p of game.patrols){circle(p.x,p.y,100,'#eec07813');circle(p.x,p.y,17,'#ebc27f');circle(p.x,p.y,6,'#273442');ctx.strokeStyle='#eec07842';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+85,p.y+50);ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-85,p.y+50);ctx.stroke();}
 for(const s of game.strikes){const live=s.t>0;circle(s.x,s.y,43,live?'#ef785528':'#ef7855a0');circle(s.x,s.y,43,live?'#ef9e78':'#ffc292',true);if(live){ctx.strokeStyle='#ef9e78';ctx.beginPath();ctx.moveTo(s.x-15,s.y);ctx.lineTo(s.x+15,s.y);ctx.moveTo(s.x,s.y-15);ctx.lineTo(s.x,s.y+15);ctx.stroke();}}
 for(const b of game.bullets){circle(b.x,b.y,7,'#f2a66f');circle(b.x,b.y,12,'#f2a66f25');}
 if(game.chapter>=5&&game.character!=='graybird')sprite('graybird',game.bird.x,game.bird.y,58);
 const team=characters.filter(c=>c.id!==game.character&&c.id!=='graybird');team.slice(0,6).forEach((c,i)=>{const x=game.player.x-30-(i%3)*22,y=game.player.y+25+Math.floor(i/3)*25;ctx.save();ctx.globalAlpha=.55;sprite(c.id,x,y,35);ctx.restore();});
 circle(game.player.x,game.player.y+13,20,'#0006');if(game.shield>0)circle(game.player.x,game.player.y-10,45,'#b4d9ec',true);if(game.stealth>0)ctx.globalAlpha=.55;if(game.invulnerable>0&&!reduced)ctx.globalAlpha=.65;sprite(game.character,game.player.x,game.player.y,74);ctx.globalAlpha=1;circle(game.player.x,game.player.y+20,3,'#c9e8f6');
 if(game.mode==='finale'){ctx.fillStyle='#354452';ctx.fillRect(385,75,190,12);ctx.fillStyle='#c4b4ef';ctx.fillRect(385,75,190*game.bossHp/12,12);text('敌方封锁信号',480,106,12,'#bbafdf');}
 if(game.status==='paused'){ctx.fillStyle='#0006';ctx.fillRect(camX,camY,W,H);}ctx.restore();
 if(W<960){const dx=(game.mode==='collect'?game.items.find(n=>!n.done)||game.exit:game.nodes.find(n=>!n.done)||{x:480,y:320}).x-camX;const target=game.mode==='collect'?game.items.find(n=>!n.done)||game.exit:game.nodes.find(n=>!n.done)||{x:480,y:320};if(dx>W-35){text('目标 →',W-45,34,12,'#e8b77c');}else if(dx<35){text('← 目标',45,34,12,'#e8b77c');}}
}
Object.defineProperty(window,'rescueState',{get:()=>Object.freeze(game.snapshot())});
boot();
