#!/usr/bin/env python3
"""Build additive EN/JA homepages. Existing files are read-only inputs."""
import html, json, re
from pathlib import Path
from html.parser import HTMLParser
ROOT = Path(__file__).resolve().parents[1]
HAN = re.compile(r'[\u4e00-\u9fff]')
LITERAL = re.compile(r"'((?:[^'\\]|\\.)*)'")
COPY = json.loads((ROOT/'i18n/home-copy.json').read_text())
by_zh = {row['zh']:row for row in COPY}

def scan_inventory():
    records=[]
    class Scanner(HTMLParser):
        def __init__(self,path):
            super().__init__(); self.path=path; self.excluded=0
        def add(self,text,kind):
            if HAN.search(text):
                records.append({'key':f'inventory.{len(records):04d}','zh':text,'file':self.path,'line':self.getpos()[0],'kind':kind})
        def handle_starttag(self,tag,attrs):
            if tag in ('style','script'): self.excluded+=1
            for name,value in attrs:
                if value and name in ('alt','aria-label','content','title','placeholder'): self.add(value,'attribute:'+name)
        def handle_endtag(self,tag):
            if tag in ('style','script'): self.excluded=max(0,self.excluded-1)
        def handle_data(self,text):
            if not self.excluded: self.add(text.strip(),'text')
    for path in sorted(ROOT.rglob('*')):
        if any(part in ('en','ja','i18n','.git','.agents') for part in path.relative_to(ROOT).parts): continue
        relative=str(path.relative_to(ROOT))
        if path.suffix=='.html': Scanner(relative).feed(path.read_text())
        elif path.suffix in ('.js','.mjs'):
            text=path.read_text()
            for match in re.finditer(r"(['\"`])((?:[^\\]|\\.)*?)\1",text):
                if HAN.search(match[2]): records.append({'key':f'inventory.{len(records):04d}','zh':match[2],'file':relative,'line':text.count('\n',0,match.start())+1,'kind':'script-string'})
        elif path.suffix=='.json':
            for number,line in enumerate(path.read_text().splitlines(),1):
                if HAN.search(line): records.append({'key':f'inventory.{len(records):04d}','zh':line.strip(),'file':relative,'line':number,'kind':'data'})
    (ROOT/'i18n/copy-inventory.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')

def main():
    source=(ROOT/'index.html').read_text()
    js=(ROOT/'script.js').read_text()
    # The one dynamic Chinese template literal is outside single-quoted strings.
    js=js.replace('`查看${figure.querySelector(\'h4\').textContent}完整画面`', '`${window.GRAYBIRD_COPY.viewPrefix}${figure.querySelector(\'h4\').textContent}${window.GRAYBIRD_COPY.viewSuffix}`')
    def literal(match):
        value=match[1]
        if not HAN.search(value): return match[0]
        if value not in by_zh: raise ValueError('Missing script translation: '+value)
        return 'window.GRAYBIRD_COPY['+json.dumps(by_zh[value]['key'])+']'
    js=LITERAL.sub(literal,js)
    if HAN.search(js): raise ValueError('Untranslated runtime copy')
    (ROOT/'i18n/home-runtime.js').write_text('// Generated by scripts/build_locales.py; do not edit.\n'+js)
    for lang in ('en','ja'):
        text=source
        # A single regex pass prevents shorter strings corrupting compound translations.
        pattern=re.compile('|'.join(re.escape(key) for key in sorted(by_zh,key=len,reverse=True) if '\\n' not in key))
        text=pattern.sub(lambda m: html.escape(by_zh[m[0]][lang],quote=True),text)
        text=text.replace('lang="zh-CN"',f'lang="{lang}"',1)
        # Explicit absolute resources preserve the original directory routing and hashes.
        text=re.sub(r'(href|src|srcset)="(assets/|styles.css|status-notice.css|community.css|game-entry.css|scroll.js)',r'\1="/\2',text)
        text=text.replace('src="script.js?v=4-art-restored-1"','src="/i18n/home-runtime.js?v=1"')
        canonical=f'https://graybird.space/{lang}/'
        text=text.replace('href="https://graybird.space/"',f'href="{canonical}"',1)
        text=text.replace('property="og:url" content="https://graybird.space/"',f'property="og:url" content="{canonical}"')
        text=text.replace('"url":"https://graybird.space/"',f'"url":"{canonical}"')
        text=text.replace('"inLanguage":["zh-CN","en"]',f'"inLanguage":"{lang}"')
        if lang=='ja':
            text=text.replace('Graybird — Interactive Earth Observation System','Graybird — 地球観測システム')
            text=text.replace('A gray bird arrived on Earth.<br>Now he\'s watching us.','灰色の鳥が地球に来た。<br>今、人間を見ている。')
            text=text.replace('Garybird is temporarily offline.','Graybirdは一時オフライン。')
            text=text.replace('A gray bird arrived on Earth. Now he\'s watching us.','灰色の鳥が地球に来た。今、人間を見ている。')
            text=text.replace('Somewhere between Earth and the Internet.','地球とネットの、どこかで。')
        # Retain legacy author names in the Chinese source; use the official brand in additions.
        text=text.replace('Garybird','Graybird')
        alternates='\n'.join(f'<link rel="alternate" hreflang="{code}" href="https://graybird.space/{path}">' for code,path in [('zh',''),('en','en/'),('ja','ja/'),('x-default','')])
        data={row['key']:row[lang] for row in COPY}
        data.update(viewPrefix='View ' if lang=='en' else '',viewSuffix=' — full scene' if lang=='en' else 'の画像全体を見る')
        payload=json.dumps(data,ensure_ascii=False).replace('<','\\u003c')
        extra=alternates+'\n<link rel="stylesheet" href="/i18n/locales.css">\n<script>window.GRAYBIRD_COPY='+payload+';</script>\n<script src="/i18n/languages.js" defer></script>\n'
        text=text.replace('</head>',extra+'</head>')
        switch='<details class="language-picker"><summary aria-label="'+('Choose language' if lang=='en' else '言語を選ぶ')+'">🌐 '+lang.upper()+'</summary><nav aria-label="'+('Languages' if lang=='en' else '言語')+'">'+''.join(f'<a href="{path}" lang="{code}" data-language="{code}"'+(' aria-current="page"' if code==lang else '')+'>'+label+'</a>' for code,path,label in [('zh','/','中文'),('en','/en/','EN'),('ja','/ja/','JA')])+'</nav><p class="language-recommendation" role="status" hidden></p></details>'
        text=text.replace('</nav>\n</header>','</nav>\n'+switch+'\n</header>',1)
        # Chinese is a language endonym, intentionally present in the language chooser only.
        (ROOT/lang/'index.html').write_text(text)
    sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
    for lang in ('en','ja'):
        sitemap+=f'<url><loc>https://graybird.space/{lang}/</loc>'
        for code,path in [('zh',''),('en','en/'),('ja','ja/'),('x-default','')]:sitemap+=f'<xhtml:link rel="alternate" hreflang="{code}" href="https://graybird.space/{path}"/>'
        sitemap+='</url>\n'
    (ROOT/'i18n/sitemap.xml').write_text(sitemap+'</urlset>\n')
    scan_inventory()
    print('Built /en/ and /ja/ from the read-only homepage and script; scanned original site copy.')
if __name__=='__main__':main()
